### ISSUE TITLE
Capturing wildcards clarification.

### ISSUE THREAD

**Issue by mariusursache** [silentrob/superscript-editor#16]
Need clarification on which wildcards are capturable.

Currently, the current [SuperScript docs](http://superscriptjs.com/documentation/scripting#variable) are a bit confusing on this matter:

![image](https://cloud.githubusercontent.com/assets/867133/7704503/3ba52636-fe15-11e4-8a31-1a283e5a2912.png)

then 

![image](https://cloud.githubusercontent.com/assets/867133/7704523/5a578402-fe15-11e4-9505-3427c6d633d7.png)

And your comment in #14:

> Variable length wildcards should not capture data at all. Perhaps displaying undefinedis a bug. This functionality is by design, and is documented in the docs. The workaround is to use (*~2) This is also the same for open wildcards \* anything that can be zero is skipped.

Testing the following scenarios with the user input `Hello John` with the same `hello back <cap>` reply:

| Trigger | Input | Reply |
| --- | --- | --- |
| `hello *~2` | Hello John Doe | Hello back John Doe |
| `hello *~2` | Hello John | Hello back John |
| `hello *~2` | Hello | _Does not match!_ See #15 |
| `hello (*~2)` | Hello John Doe | Hello back John Doe |
| `hello (*~2)` | Hello John | Hello back John |
| `hello (*~2)` | Hello | Does not match |
| `hello *1` | Hello John | Hello back john |
| `hello *` | Hello John | Hello back undefined |

This is from a previous reply on chatbots.org and makes things clear (also SS works this way now—tested:
- \* does not capture data
- *n captures
- *~n captures
- [a|b] does not capture
- (a|b) captures
- ~wordnet captures

Let me know if this is right, and I will update the wiki draft documentation with it.

**Comment by mariusursache** [comment]
Ah... regarding this:

> Only wildcards that are NOT ZERO length can be used to capture input. So wildcards will not capture the text back, but exact length wildcards and optionals will capture the input.

Actually optionals don't capture the input right now. Maybe they should, though...
Right now, capturing works for variable-length, fixed-length wildcards, alternates and wordnet.

**Comment by silentrob** [comment]
Correct. I had an issue trying to capture zero length things because we gobble up the sentence boundary and I don't know if we are capturing the word in question, or the next word - false positive.

Here are the tests for wildcard behaviour.
https://github.com/silentrob/superscript/blob/master/test/script.js#L9-L210
And the fixture https://github.com/silentrob/superscript/blob/master/test/fixtures/script/script.ss

Also, relevant Ive added matching interface just a few weeks back and is slightly more powerful, but has yet to be documented.

Min/Max Wildcards
`*(n-m)` Where n is min, and m is max.
https://github.com/silentrob/superscript/blob/master/test/script.js#L114-L143

I believe `*(n)` defaults to exact match behaviour.

**Comment by mariusursache** [comment]
I am documenting the new behavior in the new documentation. We can close this issue.
